# Generated by Django 3.0.4 on 2020-03-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redis_test_app', '0002_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='login',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='exaple@mail.ru', max_length=254),
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
