# Generated by Django 3.0.4 on 2020-03-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redis_test_app', '0003_auto_20200329_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='university',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
